language: java
install: true

before_install:
  - for deb in deb deb-src; do echo "$deb http://build.openmodelica.org/apt `lsb_release -cs` release"; done | sudo tee /etc/apt/sources.list.d/openmodelica.list
  - wget -q http://build.openmodelica.org/apt/openmodelica.asc -O- | sudo apt-key add - 
  - sudo apt-get update
  - sudo apt-get install openmodelica
  - sudo apt-get install omc-java
  - sudo apt-get install omlib-modelica-3.2.2

cache:
  directories:
  - $HOME/.m2

env:
  - OPENMODELICAHOME=/usr/
script:
  - mvn package -B
before_deploy:
  - mvn help:evaluate -N -Dexpression=project.version | grep -v '\['
  - export project_version=$(mvn help:evaluate -N -Dexpression=project.version | grep -v '\[')

deploy:
  provider: releases
  api_key:
    secure: DFAKRA8zSwM3d4pMm7Mkye6rrgjv6PD1ExyZBKawX4bTGAefFcdiE35bUR+AViskongLtTMyThmtxkMYSm9f9+tYwN3Age6sqZiiZO9MxhCkgA60Z605KQKLlEavGYJQQhsXur9IEQ71hG5x401er6q7WFwAukS9HYkDEIONjNGGsSIhZHPZfPJU5c0TwzJHZLnYnHUWS0bbZ878UeNme7fwDGh968DEPGvvRPJ9ELxzOO52xv0BafKbtdMwxyercB/TBEoA8RNjzlZEHnSAvr2RHfhVKn/E23Yl3tW5OdY6nG2AgH+83PGAjWORmmlvRM9+ITBR/L8X/NE03aXHTz1BG7o/UONmILjmbz9U+PniTAFH+xcsWTMtDGF3hUkvzKj8tJ8GugB2MYcfkWm2gUAPuBWkH5z4Hb6nffXKYVEMy5E5fjUdDSlXKhLbMOVf6JwlJYOi7Y7z1YUKj0w01+DzLl2Ia1YBaUAIP1S4lwEGbc93S1ZNlWGhkHLY01xeBANSRZVC7BcUQM0EFHBLog/oh8hiG8rHIK0SQm9JXoc+mhfOWuvg+vsRP9YklRENui7PfR0Zwd8PYrQE5/VDygenpLt0rd0OOHtNDu6lMK8YAR9iucPGpRglZfxk7wrjd8fonW0ywwB6SBiAZYywX6gLZ1sNZ4MhbKvAUP2plI8=
  file: "build/RaspInLoop/OMJava/target/OMJava-$project_version.jar"
  skip_cleanup: true
  overwrite: true
  on:
    repo: RaspInLoop/OMJava
    tag: true
  name: $project_version
