language: java
install: true

before_install:
  - for deb in deb deb-src; do echo "$deb http://build.openmodelica.org/apt `lsb_release -cs` release"; done | sudo tee /etc/apt/sources.list.d/openmodelica.list
  - wget -q http://build.openmodelica.org/apt/openmodelica.asc -O- | sudo apt-key add - 
  - sudo apt-get update
  - sudo apt-get install openmodelica
  - sudo apt-get install omc-java
  - sudo apt-get install omlib-modelica-3.2.2

cache:
  directories:
  - $HOME/.m2

env:
  - OPENMODELICAHOME=/usr/
  
script: 
  - mvn install -B
  
